
server:
  port: 0
spring:
  application:
    name: community-service
  datasource:
    url: jdbc:mysql://localhost:3306/Community?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
